### ISSUE TITLE
Method name modification suggestions

### ISSUE THREAD

**Issue by elgca** [nguyenyou/scalawind#134]
I learning scalajs recently, using my favorite language scala, no js.
i found this project, it is a good idea，can focus on scalajs code
I used your template to generate bootstrap CSS and other CSS for me, using SBT.
I have some suggestions:

1. We should apply Scala's feature of using any name as a method name through symbols ``` , There is a conflict between `per` and `dot`
```scala
  def `table-sort`: BtsClass = this
```
used like :
![image](https://github.com/nguyenyou/scalawind/assets/22080060/a14d260f-0901-4bfd-8ba3-bb5af20e3447)

2. provide `extension` replace `implicit` or both,  it not work in laminar.
```scala
extension (inline btsClass: BtsClass)
  inline def css: String =
    ${ btspImpl('btsClass) }
```

3.  Consider watching CSS files and updating the 'scalawind. scala' file during encoding.
4.  We can support all CSS files, not tailwind only, Just like what I'm doing in bootstrap now. make tailwind to generate a complete CSS, so that tailwindcss can also benefit from it. Now I am using 'com. helper'% 'ph css', a Java library
5.  SBT or Mill Plugin?

**Comment by nguyenyou** [comment]
Hi @elgca! 

Thank you very much for your suggestions, all are great. I'll try do implement them.

**Comment by nguyenyou** [comment]
Hi @elgca!

Suggestion 1, is repleased in `v0.8.2` version. Thank you very much. 

Suggestion 2, I really hope it works. Could you contribute or give me a link to a public repo that successfully achieve this? It would be very helpful. __Sorry for my limited knowledge of Scala.__

Suggestion 4, it's really interesting, I really want to see how you do it in your project, can you open source a small project that applies the technique? I would love to learn the trick.

Suggestion 3, I think we can do that.

Suggestion 5, I think I will try to do this when I'm getting more familiar with SBT and Mill.

**Comment by elgca** [comment]
I find it difficult to provide any professional advice for real-time translation of 112/10000. In fact, I have been studying network technology for less than a month. 2 and 4, I will create a repository later, which is a pre compiled class in the SBT project, using the generator code and CSS parser demonstrated in the seminar. Translation: I find it difficult to give any professional advice, in fact, I have only been learning web technology for less than a month. 2 and 4, I will create a repository later, This is a pre compiled class in the SBT project, using the generator code from the seminar demo and a CSS parser.

**Comment by elgca** [comment]
https://github.com/elgca/bootstrap-css-importor

**Comment by nguyenyou** [comment]
Thank you @elgca , the library is much better with your help.

**Comment by elgca** [comment]
This project is very meaningful. Unlike JavaScript, scalajs does not have a lot of user-friendly IDE support, and this project compensates for some of it. Based on my current feeling, we need a powerful preset framework like bootstrap, as well as a flexible solution like tailwind to modify the details. I have added an extension to enable the generated bootstrap CSS class to be integrated with the scalawind.class, and the results are very interesting when they work simultaneously.

**Comment by nguyenyou** [comment]
> Based on my current feeling, we need a powerful preset framework like bootstrap
Have you heard about [daisyUI](https://daisyui.com/components/button/), it's a really good Tailwind Plugin which contains a lot of pre-built components. I added an example integrated with daisyUI:

```bash
npx degit nguyenyou/scalawind/examples/vite-app-daisy daisyapp
```

For example, a button can be used like this:

```scala
button(
  cls := tw.btn.btn_primary.css,
  "Click me"
)
```

**Comment by elgca** [comment]
Just now, from you:)
Thank you example, I will take a look.

**Comment by nguyenyou** [comment]
@elgca I just want to let you know that, I've just added some magic to the library, so that, the syntax is super clean, like this:

```scala
div(
  tw.text_red_500.bg_black,
  "Hello world"
)
```

Yes! We can omit the `cls :=` and `.css` part, leaving just the tailwind classes.
